FROM tomcat:8.5-jre8
COPY commandproc/commandproc.war /usr/local/tomcat/webapps
COPY commandproc/start-commandproc.sh /usr/local/tomcat/start-commandproc.sh 
RUN chmod +x /usr/local/tomcat/start-commandproc.sh 
RUN chown -R www-data:www-data /usr/local/tomcat/logs
RUN chown -R www-data:www-data /usr/local/tomcat/webapps
RUN chown -R www-data:www-data /usr/local/tomcat/work
EXPOSE 8080
ENTRYPOINT ["/bin/bash","-c","/usr/local/tomcat/start-commandproc.sh" ]
