FROM tomcat:8.5-jre8
COPY commandproc/commandproc.war /usr/local/tomcat/webapps
RUN echo "user=coinminer" > /etc/credentials.properties
RUN echo password=$(openssl rand -hex 32) >> /etc/credentials.properties
EXPOSE 8080
